### ISSUE TITLE
open the relevant toggles when jumping to the setting?

### ISSUE THREAD

**Issue by eleanorkonik** [valentine195/obsidian-settings-search#11]
I don't know if this is possible, but it would be amazing if this plugin could help me solve this problem: 

![settings-search](https://user-images.githubusercontent.com/75856959/156884214-0619a233-75a0-4c53-9dba-39ef72df058d.gif)

I know Breadcrumbs HAS this setting, I just can't _find_ it in this wall of toggles.

**Comment by valentine195** [comment]
Thanks for letting me know! I can handle this similar to how I handle it in Style Settings :)

**Comment by eleanorkonik** [comment]
@luckman212 it's primary, winner of Obsidian October :D

**Comment by valentine195** [comment]
Sorry, I completely forgot about this!
