### ISSUE TITLE
Issue with Settings Search 'go to' arrows

### ISSUE THREAD

**Issue by Quisquose** [valentine195/obsidian-settings-search#16]
When searching for a term that matches a plugin name, in the matched results I get a cog icon (to access the plugin's options/settings) and an arrow icon (presumably to go to the plugin's entry in the Community Plugins section).

However, whenever I use the arrow icon for any plugin, it never actually takes me to that plugin's entry, but rather it just dumps me at the beginning of the Community Plugins list, where I then have to manually scroll through all the entries to find the plugin for myself.

I'm not sure whether this is by design or not, but it would be good if the arrow icon in the Settings Search results took you to the general Community Plugins section ***and*** scrolled you down to the correct specific plugin entry.

Thanks.

**Comment by oldwinter** [comment]
same with you~~

**Comment by a13ph** [comment]
It seems that arrow jump scrolls to selected plugin correctly (and even highlights it, but then scrolls back to top.

Options that I see:
1) Delaying jump event.
2) Duplicating jump event after a delay.
3) Setting plugin list's search field to exact name of selected plugin (if possible).
4) Utilizing Advanced URI with it's ability to jump directly to any plugin's settings given its ID.

**Comment by nhan000** [comment]
same :(

**Comment by Ali-C-Ila** [comment]
That problem doesn't exist for me now. Can close this?

**Comment by valentine195** [comment]
This should be fixed
