### ISSUE TITLE
Settings Search 1.2.0 appears to break some other plugins in Obsidian 0.15.1

### ISSUE THREAD

**Issue by claremacrae** [valentine195/obsidian-settings-search#17]
Hello,

I just logged these issues in other plugins, and in both cases, turning off Settings Search and re-starting made the issues go away:

- https://github.com/phibr0/obsidian-macros/issues/9
- https://github.com/Taitava/obsidian-shellcommands/discussions/233

Setup

- Obsidian 0.15.1 (Insider)
- Settings Search 1.2.0

**Comment by valentine195** [comment]
Settings search renders settings tabs on load in order to grab settings elements. If a plugin has errors in their settings tabs, they will show up here.

**Comment by claremacrae** [comment]
@valentine195 Just a thought, you may be about to get a bunch of messages like mine - is there any possibility you could add to the error message to say something like "please report the issue to the other plugin"?
