### ISSUE TITLE
[feature] Jump to the line instead of only jumping to the page.

### ISSUE THREAD

**Issue by Ali-C-Ila** [valentine195/obsidian-settings-search#21]
## usecase
Nice plugin. Currently, it is capable of searching & jumping to the correct settings page. 
But when dealing with really-long settings pages (namely, Excalidraw and Style settings), only jumping to the right page still leaves an awful lot of reading and scrolling to do.

## proposed solution
When clicking the link from search result, jump to the exact line that contains your query, instead of only jumping to the page.

**Comment by Palvehelmed** [comment]
+1, it works well on iOS mobile for jumping to the right line in long setting pages like "style setting", but it jumps back unexpectedly to the main page on macOS Obsidian. A video can be uploaded if necessary.

**Comment by gchegr** [comment]
Please make it jump to the found block and also highlight it for a second or two with a border or a padding, fading out.

**Comment by valentine195** [comment]
This should be fixed now
