### ISSUE TITLE
Conflict with obsidian-enhancing-export plugin, app gets unresponsive

### ISSUE THREAD

**Issue by victorstan** [valentine195/obsidian-settings-search#33]
Please try to install [obsidian-enhancing-export](https://github.com/mokeyish/obsidian-enhancing-export) plugin and you'll notice that the UI is unresponsive and there are some errors in the console. More details [here](https://github.com/mokeyish/obsidian-enhancing-export/issues/49)

**Comment by valentine195** [comment]
See https://github.com/mokeyish/obsidian-enhancing-export/issues/49#issuecomment-1476259901

I can recreate this without Settings Search installed.

**Comment by luckman212** [comment]
I had this today, different plugin conflict though. See #41
